tput setaf 1;echo "-----------------------------------------------------------------------------------------------------------------------------"
echo ""
tput setaf 6;echo "Welcome to the Azure Firewall TLS inspection scenario!"
echo ""
tput setaf 6;echo "* To check the configuration deployment log, use the 'cat jumpstart_logs/installKubeadm.log' command."
echo ""
tput setaf 6;echo "* To work with the AKS cluster, use the 'kubectl <command>'. For example: kubectl get nodes"
echo ""
tput setaf 1;echo "-----------------------------------------------------------------------------------------------------------------------------"